# Use the PHP 7.4 runtime
runtime: php74

# Defaults to "serve index.php" 
# entrypoint: serve homescreen.php

# If your main page is index.php, comment the above entrypoint setting

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
# - url: /.*
#   script: auto
#   options:
#     session_affinity: true
